## 1. Import all needed Libraries/Module

In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import numpy

## 2. Read data, and then do some explanatory data analysis

In [6]:
data=pd.read_csv('./data/clean.csv',header=0,index_col=0)
data

,DC024,DC025,DC205,DC206,DC207,DC208,DC209,DC210,DC211,DC212,...,DC237f,DC241,DC242,DC244,DC246,DC252,DC270a,DC109,DC142a,DC201
0,11,2,16.0,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,1.0,0.000000,0.000000,0.000000,2.000000,1,12.000000,60.000000,0
1,11,2,31.0,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.0,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,2,31.000000,70.000000,0
2,11,2,12.0,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.0,...,0.000000,1.0,0.000000,1.000000,1.000000,0.000000,4,11.000000,75.000000,0
3,11,2,12.0,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.0,...,0.000000,2.0,1.000000,1.000000,0.000000,1.000000,1,11.000000,85.000000,0
4,11,2,12.0,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.0,...,0.000000,1.0,0.000000,0.000000,1.000000,0.000000,2,11.000000,65.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64791,33,2,12.0,1.000000,0.334627,1.000000,0.665373,0.000000,1.000000,0.0,...,0.665373,1.0,1.000000,1.000000,0.334627,1.000000,3,11.000000,133.338509,1
64792,14,2,12.0,1.000000,0.000000,1.000000,0.000000,0.999670,1.000000,0.0,...,0.999670,1.0,1.000000,1.000000,1.000000,1.000000,2,11.000000,71.999340,1
64793,77,2,31.0,1.000000,0.747717,0.000000,0.000000,0.252283,0.000000,0.0,...,0.747717,1.0,0.747717,1.000000,1.000000,0.252283,1,31.252283,25.513698,1
64794,12,2,21.0,0.184086,0.000000,0.184086,0.000000,0.000000,0.000000,0.0,...,0.000000,1.0,1.000000,0.815914,0.000000,1.000000,1,41.000000,64.288604,1
64795,64,2,31.0,0.144417,0.000000,0.000000,0.000000,0.855583,0.144417,0.0,...,0.144417,1.0,0.855583,0.855583,1.000000,1.000000,1,51.000000,24.866504,1

In [7]:
# gather information about data attribute
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 64796 entries, 0 to 64795
Data columns (total 39 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   DC024   64796 non-null  int64
 1   DC025   64796 non-null  int64
 2   DC205   64796 non-null  float64
 3   DC206   64796 non-null  float64
 4   DC207   64796 non-null  float64
 5   DC208   64796 non-null  float64
 6   DC209   64796 non-null  float64
 7   DC210   64796 non-null  float64
 8   DC211   64796 non-null  float64
 9   DC212   64796 non-null  float64
 10  DC213   64796 non-null  float64
 11  DC214   64796 non-null  float64
 12  DC215   64796 non-null  float64
 13  DC216   64796 non-null  float64
 14  DC217   64796 non-null  int64
 15  DC219   64796 non-null  int64
 16  DC220   64796 non-null  float64
 17  DC226   64796 non-null  float64
 18  DC230a  64796 non-null  float64
 19  DC230b  64796 non-null  float64
 20  DC232   64796 non-null  float64
 21  DC232b  64796 non-null  float64
 22  DC235   64796 non-null  float64
 23  DC237   64796 non-null  float64
 24  DC237a  64796 non-null  float64
 25  DC237b  64796 non-null  float64
 26  DC237c  64796 non-null  float64
 27  DC237d  64796 non-null  float64
 28  DC237e  64796 non-null  float64
 29  DC237f  64796 non-null  float64
 30  DC241   64796 non-null  float64
 31  DC242   64796 non-null  float64
 32  DC244   64796 non-null  float64
 33  DC246   64796 non-null  float64
 34  DC252   64796 non-null  float64
 35  DC270a  64796 non-null  int64
 36  DC109   64796 non-null  float64
 37  DC142a  64796 non-null  float64
 38  DC201   64796 non-null  int64
dtypes: float64(33), int64(6)
memory usage: 19.8 MB

Dari data di atas, dapat dilihat bahwa semua data bertipe data flloat/integer, dan label bertipe data string.

## Cari informasi apakah ada data yang bernilai null/kosong

In [9]:
data.isnull().sum()

DC024     0
DC025     0
DC205     0
DC206     0
DC207     0
DC208     0
DC209     0
DC210     0
DC211     0
DC212     0
DC213     0
DC214     0
DC215     0
DC216     0
DC217     0
DC219     0
DC220     0
DC226     0
DC230a    0
DC230b    0
DC232     0
DC232b    0
DC235     0
DC237     0
DC237a    0
DC237b    0
DC237c    0
DC237d    0
DC237e    0
DC237f    0
DC241     0
DC242     0
DC244     0
DC246     0
DC252     0
DC270a    0
DC109     0
DC142a    0
DC201     0
dtype: int64

## Cari korelasi tiap atribut dengan pandas corr

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
data=pd.DataFrame(scaler.fit_transform(temp),columns=temp.columns)
data

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0         0.222222      0.625000       0.067797      0.041667      0.0
1         0.166667      0.416667       0.067797      0.041667      0.0
2         0.111111      0.500000       0.050847      0.041667      0.0
3         0.083333      0.458333       0.084746      0.041667      0.0
4         0.194444      0.666667       0.067797      0.041667      0.0
..             ...           ...            ...           ...      ...
145       0.666667      0.416667       0.711864      0.916667      1.0
146       0.555556      0.208333       0.677966      0.750000      1.0
147       0.611111      0.416667       0.711864      0.791667      1.0
148       0.527778      0.583333       0.745763      0.916667      1.0
149       0.444444      0.416667       0.694915      0.708333      1.0

[150 rows x 5 columns]

In [25]:
#Split dataset menjadi training dan testing
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(data.drop('DC201',axis=1),data['DC201'],test_size=0.2)
x_train.shape,y_train.shape

((51836, 38), (51836,))

In [26]:
import torch
from torch import nn

In [27]:
x_train,x_test,y_train,y_test=torch.Tensor(x_train.values),torch.Tensor(x_test.values),torch.Tensor(y_train.values),torch.Tensor(y_test.values)
x_train.shape,y_train.shape

(torch.Size([51836, 38]), torch.Size([51836]))

In [28]:
y_train,y_test=y_train.to(int),y_test.to(int)
y_train

tensor([1, 0, 1,  ..., 1, 0, 0])

In [29]:
# Create class model

class Baseline(nn.Module):
    def __init__(self,input_shape:int=4,output_shape:int=3) -> None:
        super().__init__()
        self.layer=nn.Sequential(
            nn.Linear(in_features=input_shape,
                      out_features=output_shape),
        )
    def forward(self,x):
        return self.layer(x)

In [30]:
model=Baseline(input_shape=x_train.shape[1],output_shape=2)
#setup loss function
loss_fn=nn.CrossEntropyLoss()
#setup optimizer
optimizer=torch.optim.SGD(params=model.parameters(),lr=0.01)

In [36]:
device='cpu'

In [37]:
def train_step(model:nn.Module,
               dataloader:torch.utils.data.DataLoader,
               loss_fn:nn.Module,
               accuracy_fn,
               optimizer:torch.optim.Optimizer,
               device:torch.device=device
               ):
    train_acc,train_loss=0,0
    # iterate each batch
    for batch,(X,y) in enumerate(dataloader):
        X,y=X.to(device),y.to(device)
    
        # Forward pass
        y_pred=model(X)
        # calculate the loss
        loss=loss_fn(y_pred,y)
        train_loss+=loss.item()
        train_acc+=accuracy_fn(y_true=y,y_pred=y_pred.argmax(dim=1))

        # Optimizer zero grad
        optimizer.zero_grad()

        # Loss backward step
        loss.backward()

        # optimizer step
        optimizer.step()
    train_loss=train_loss/len(dataloader)
    train_acc=train_acc/len(dataloader)
    print(f' Train Accuracy : {train_acc}\n Train Loass : {train_loss}')
    return train_acc,train_loss

In [ ]:
def test_step(model:nn.Module,
              dataloader:torch.utils.data.DataLoader,
              loss_fn:nn.Module,
              accuracy_fn,
              device:torch.device=device):
    test_acc, test_loss=0,0
    with torch.inference_mode():
        for X,y in dataloader:
            X,y=X.to(device),y.to(device)
            y_pred=model()

In [33]:
from tqdm.auto import tqdm
EPOCHS=10
train_acc=[]
test_acc=[]
train_loss=[]
test_loss=[]

for epoch in tqdm(range(EPOCHS)):
    model.train()
    y_pred=model(x_train)
    loss=loss_fn(y_pred,y_train)
    loss_value=loss.item()
    train_loss.append(loss_value)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    acc = (torch.softmax(y_pred,dim=1).argmax(dim=1)==y_train).sum().float() / len(y_train) 
    train_acc.append(acc)
    model.eval()

    y_pred_test=model(x_test)
    loss=loss_fn(y_pred_test,y_test)
    test_loss_value=loss.item()
    test_loss.append(test_loss_value)
    test_acc_value= (torch.softmax(y_pred_test,dim=1).argmax(dim=1)==y_test).sum().float() / len(y_test) 
    train_acc.append(test_acc_value)
    print(f'Training in epoch : {epoch} with Accuracy {acc} and Loss {loss_value}\n Test Accuracy {test_acc_value} Test loss {test_loss_value}')

100%|██████████| 10/10 [00:00<00:00, 47.60it/s]

Training in epoch : 0 with Accuracy 0.6585384607315063 and Loss 6.857609272003174
 Test Accuracy 0.6608796119689941 Test loss 9.8423433303833
Training in epoch : 1 with Accuracy 0.6655413508415222 and Loss 9.868230819702148
 Test Accuracy 0.49606481194496155 Test loss 17.103729248046875
Training in epoch : 2 with Accuracy 0.5013311505317688 and Loss 17.1307373046875
 Test Accuracy 0.530632734298706 Test loss 38.606021881103516
Training in epoch : 3 with Accuracy 0.5285901427268982 and Loss 38.57455062866211
 Test Accuracy 0.6611111164093018 Test loss 6.758094787597656
Training in epoch : 4 with Accuracy 0.658577024936676 and Loss 6.8517022132873535
 Test Accuracy 0.6613426208496094 Test loss 9.932992935180664
Training in epoch : 5 with Accuracy 0.6652905344963074 and Loss 9.956876754760742
 Test Accuracy 0.49606481194496155 Test loss 17.070154190063477
Training in epoch : 6 with Accuracy 0.5013311505317688 and Loss 17.097658157348633
 Test Accuracy 0.5304012298583984 Test loss 38.63191604614258
Training in epoch : 7 with Accuracy 0.5285515785217285 and Loss 38.60114669799805
 Test Accuracy 0.6608024835586548 Test loss 6.750711441040039
Training in epoch : 8 with Accuracy 0.6585191488265991 and Loss 6.844420433044434
 Test Accuracy 0.6611882448196411 Test loss 9.938618659973145
Training in epoch : 9 with Accuracy 0.6653484106063843 and Loss 9.96231460571289
 Test Accuracy 0.49606481194496155 Test loss 17.06443214416504